server:
  port: 2080
spring:
  cloud:
    gateway:
      routes:
        - id: userCmdApi-RegisterUser
          uri: http://localhost:8081/api/v1/register-user
          predicates:
            - Path=/api/v1/register-user
        - id: userCmdApi-UpdateUser
          uri: http://localhost:8081/api/v1/update-user/**
          predicates:
            - Path=/api/v1/update-user/**
        - id: userCmdApi-RemoveUser
          uri: http://localhost:8081/api/v1/remove-user/**
          predicates:
            - Path=/api/v1/remove-user/**
        - id: userQueryApi
          uri: http://localhost:8082/api/v1/user-search/**
          predicates:
            - Path=/api/v1/user-search/**

springdoc:
  swagger-ui:
    path: /swagger-doc/swagger-ui.html
  api-docs:
    path: /swagger-doc/v3/api-docs